volumes:
  minio: {}

services:
  minio:
    image: minio/minio
    restart: always
    command: server --console-address ':9001' /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio:/data
    ports:
      - '9000:9000'
      - '9001:9001'

  create-minio-bucket:
    image: minio/mc
    depends_on:
      - minio
    restart: on-failure:3
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 minioadmin minioadmin;
      mc mb minio/weatheasy;
      "
